### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by SamuelSchmidgall** [ridgerchu/SpikeGPT#3]
Obtaining this error at the end of training when training bar reaches 100%

TypeError: object of type 'NoneType' has no len()

**Full error message**
```python
Traceback (most recent call last):
  File "path/pycharm-community-2021.3.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "path/pycharm-community-2021.3.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "path/PycharmProjects/LLM/train.py", line 137, in <module>
    trainer.train()
  File "path/PycharmProjects/LLM/src/trainer.py", line 183, in train
    run_epoch('valid')
  File "path/PycharmProjects/LLM/src/trainer.py", line 116, in run_epoch
    num_steps = len(loader)
  File "path/python3_venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 489, in __len__
    return len(self._index_sampler)
  File "path/python3_venv/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 265, in __len__
    return (len(self.sampler) + self.batch_size - 1) // self.batch_size  # type: ignore[arg-type]
  File "path/python3_venv/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 79, in __len__
    return len(self.data_source)
TypeError: object of type 'NoneType' has no len()
```

**Comment by ridgerchu** [comment]
Hi Samuel,

I guess it is caused by the data you used to train our model. Have you used the enwik8 for training?

**Comment by ridgerchu** [comment]
Hi Samuel,
I also notice that problem when I use my new device to run SpikeGPT. it is caused by I call the train function twice instead of once. I have updated my code and now it could function well.
